[package]
### name = "NFTLotteryContracts"
name = "DefyWaitlistContracts"
version = "1.0.0"
authors = []

[addresses]
mini_games = "0xcd7b88c2181881bf8e7ef741cae867aee038e75df94224496a4a81627edf7f65"
ticket_minter = "0x3cfc71e232191a546dd9b9cae842771d59dd3413cf8a6696a89a359849f429fd"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"


